version: '2'

services:
  postgres:
      image: "postgres:9.1"
      container_name: "postgres"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_USER=postgres
        - POSTGRES_DB=persondb
      expose:
        - 5432
      ports:
         - "5432:5432"
      restart: "always"
